coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 70%

ignore:
  - "api/v1alpha1/zz_generated.deepcopy.go"
  - "cmd/**"
  - "test/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
