# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: warpgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https # Ensure this is the name of the port that exposes HTTPS metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: false
        # To use cert-manager-issued certs, apply the patch in config/prometheus/monitor_tls_patch.yaml
        # (see config/prometheus/kustomization.yaml for instructions).
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: warpgate-operator
