---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warpgate.warpgate.warp.tech
  resources:
  - warpgateconnections
  - warpgateinstances
  - warpgatepasswordcredentials
  - warpgatepublickeycredentials
  - warpgateroles
  - warpgatetargetroles
  - warpgatetargets
  - warpgatetickets
  - warpgateuserroles
  - warpgateusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warpgate.warpgate.warp.tech
  resources:
  - warpgateconnections/finalizers
  - warpgateinstances/finalizers
  - warpgatepasswordcredentials/finalizers
  - warpgatepublickeycredentials/finalizers
  - warpgateroles/finalizers
  - warpgatetargetroles/finalizers
  - warpgatetargets/finalizers
  - warpgatetickets/finalizers
  - warpgateuserroles/finalizers
  - warpgateusers/finalizers
  verbs:
  - update
- apiGroups:
  - warpgate.warpgate.warp.tech
  resources:
  - warpgateconnections/status
  - warpgateinstances/scale
  - warpgateinstances/status
  - warpgatepasswordcredentials/status
  - warpgatepublickeycredentials/status
  - warpgateroles/status
  - warpgatetargetroles/status
  - warpgatetargets/status
  - warpgatetickets/status
  - warpgateuserroles/status
  - warpgateusers/status
  verbs:
  - get
  - patch
  - update
