# This rule is not used by the project warpgate-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the warpgate.warpgate.warp.tech.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: warpgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: warpgateconnection-editor-role
rules:
- apiGroups:
  - warpgate.warpgate.warp.tech
  resources:
  - warpgateconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warpgate.warpgate.warp.tech
  resources:
  - warpgateconnections/status
  verbs:
  - get
