## Append samples of your project ##
resources:
- warpgate_v1alpha1_warpgateconnection.yaml
- warpgate_v1alpha1_warpgaterole.yaml
- warpgate_v1alpha1_warpgateuser.yaml
- warpgate_v1alpha1_warpgatetarget.yaml
- warpgate_v1alpha1_warpgateuserrole.yaml
- warpgate_v1alpha1_warpgatetargetrole.yaml
- warpgate_v1alpha1_warpgatepasswordcredential.yaml
- warpgate_v1alpha1_warpgatepublickeycredential.yaml
- warpgate_v1alpha1_warpgateticket.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
