apiVersion: warpgate.warpgate.warp.tech/v1alpha1
kind: WarpgatePasswordCredential
metadata:
  labels:
    app.kubernetes.io/name: warpgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: warpgatepasswordcredential-sample
spec:
  connectionRef: warpgateconnection-sample
  username: john.doe
  passwordSecretRef:
    name: john-doe-password
    key: password
