apiVersion: warpgate.warpgate.warp.tech/v1alpha1
kind: WarpgateConnection
metadata:
  labels:
    app.kubernetes.io/name: warpgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: warpgateconnection-sample
spec:
  host: https://warpgate.example.com
  credentialSecretRef:
    name: warpgate-credentials
    usernameKey: username
    passwordKey: password
  insecureSkipVerify: false
