apiVersion: warpgate.warpgate.warp.tech/v1alpha1
kind: WarpgatePublicKeyCredential
metadata:
  labels:
    app.kubernetes.io/name: warpgate-operator
    app.kubernetes.io/managed-by: kustomize
  name: warpgatepublickeycredential-sample
spec:
  connectionRef: warpgateconnection-sample
  username: john.doe
  label: laptop-key
  opensshPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAEXAMPLEKEY john@laptop
