//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialPolicySpec) DeepCopyInto(out *CredentialPolicySpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialPolicySpec.
func (in *CredentialPolicySpec) DeepCopy() *CredentialPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CredentialPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTargetSpec) DeepCopyInto(out *HTTPTargetSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfigSpec)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTargetSpec.
func (in *HTTPTargetSpec) DeepCopy() *HTTPTargetSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTargetSpec) DeepCopyInto(out *MySQLTargetSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTargetSpec.
func (in *MySQLTargetSpec) DeepCopy() *MySQLTargetSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLTargetSpec) DeepCopyInto(out *PostgreSQLTargetSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLTargetSpec.
func (in *PostgreSQLTargetSpec) DeepCopy() *PostgreSQLTargetSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHTargetSpec) DeepCopyInto(out *SSHTargetSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHTargetSpec.
func (in *SSHTargetSpec) DeepCopy() *SSHTargetSpec {
	if in == nil {
		return nil
	}
	out := new(SSHTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfigSpec) DeepCopyInto(out *TLSConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfigSpec.
func (in *TLSConfigSpec) DeepCopy() *TLSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TLSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnection) DeepCopyInto(out *WarpgateConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnection.
func (in *WarpgateConnection) DeepCopy() *WarpgateConnection {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnectionCustomDefaulter) DeepCopyInto(out *WarpgateConnectionCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnectionCustomDefaulter.
func (in *WarpgateConnectionCustomDefaulter) DeepCopy() *WarpgateConnectionCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnectionCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnectionCustomValidator) DeepCopyInto(out *WarpgateConnectionCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnectionCustomValidator.
func (in *WarpgateConnectionCustomValidator) DeepCopy() *WarpgateConnectionCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnectionCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnectionList) DeepCopyInto(out *WarpgateConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnectionList.
func (in *WarpgateConnectionList) DeepCopy() *WarpgateConnectionList {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnectionSpec) DeepCopyInto(out *WarpgateConnectionSpec) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnectionSpec.
func (in *WarpgateConnectionSpec) DeepCopy() *WarpgateConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateConnectionStatus) DeepCopyInto(out *WarpgateConnectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateConnectionStatus.
func (in *WarpgateConnectionStatus) DeepCopy() *WarpgateConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredential) DeepCopyInto(out *WarpgatePasswordCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredential.
func (in *WarpgatePasswordCredential) DeepCopy() *WarpgatePasswordCredential {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgatePasswordCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredentialCustomDefaulter) DeepCopyInto(out *WarpgatePasswordCredentialCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredentialCustomDefaulter.
func (in *WarpgatePasswordCredentialCustomDefaulter) DeepCopy() *WarpgatePasswordCredentialCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredentialCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredentialCustomValidator) DeepCopyInto(out *WarpgatePasswordCredentialCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredentialCustomValidator.
func (in *WarpgatePasswordCredentialCustomValidator) DeepCopy() *WarpgatePasswordCredentialCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredentialCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredentialList) DeepCopyInto(out *WarpgatePasswordCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgatePasswordCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredentialList.
func (in *WarpgatePasswordCredentialList) DeepCopy() *WarpgatePasswordCredentialList {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgatePasswordCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredentialSpec) DeepCopyInto(out *WarpgatePasswordCredentialSpec) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredentialSpec.
func (in *WarpgatePasswordCredentialSpec) DeepCopy() *WarpgatePasswordCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePasswordCredentialStatus) DeepCopyInto(out *WarpgatePasswordCredentialStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePasswordCredentialStatus.
func (in *WarpgatePasswordCredentialStatus) DeepCopy() *WarpgatePasswordCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgatePasswordCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredential) DeepCopyInto(out *WarpgatePublicKeyCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredential.
func (in *WarpgatePublicKeyCredential) DeepCopy() *WarpgatePublicKeyCredential {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgatePublicKeyCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredentialCustomDefaulter) DeepCopyInto(out *WarpgatePublicKeyCredentialCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredentialCustomDefaulter.
func (in *WarpgatePublicKeyCredentialCustomDefaulter) DeepCopy() *WarpgatePublicKeyCredentialCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredentialCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredentialCustomValidator) DeepCopyInto(out *WarpgatePublicKeyCredentialCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredentialCustomValidator.
func (in *WarpgatePublicKeyCredentialCustomValidator) DeepCopy() *WarpgatePublicKeyCredentialCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredentialCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredentialList) DeepCopyInto(out *WarpgatePublicKeyCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgatePublicKeyCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredentialList.
func (in *WarpgatePublicKeyCredentialList) DeepCopy() *WarpgatePublicKeyCredentialList {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgatePublicKeyCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredentialSpec) DeepCopyInto(out *WarpgatePublicKeyCredentialSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredentialSpec.
func (in *WarpgatePublicKeyCredentialSpec) DeepCopy() *WarpgatePublicKeyCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgatePublicKeyCredentialStatus) DeepCopyInto(out *WarpgatePublicKeyCredentialStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgatePublicKeyCredentialStatus.
func (in *WarpgatePublicKeyCredentialStatus) DeepCopy() *WarpgatePublicKeyCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgatePublicKeyCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRole) DeepCopyInto(out *WarpgateRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRole.
func (in *WarpgateRole) DeepCopy() *WarpgateRole {
	if in == nil {
		return nil
	}
	out := new(WarpgateRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRoleCustomDefaulter) DeepCopyInto(out *WarpgateRoleCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRoleCustomDefaulter.
func (in *WarpgateRoleCustomDefaulter) DeepCopy() *WarpgateRoleCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateRoleCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRoleCustomValidator) DeepCopyInto(out *WarpgateRoleCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRoleCustomValidator.
func (in *WarpgateRoleCustomValidator) DeepCopy() *WarpgateRoleCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateRoleCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRoleList) DeepCopyInto(out *WarpgateRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRoleList.
func (in *WarpgateRoleList) DeepCopy() *WarpgateRoleList {
	if in == nil {
		return nil
	}
	out := new(WarpgateRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRoleSpec) DeepCopyInto(out *WarpgateRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRoleSpec.
func (in *WarpgateRoleSpec) DeepCopy() *WarpgateRoleSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateRoleStatus) DeepCopyInto(out *WarpgateRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateRoleStatus.
func (in *WarpgateRoleStatus) DeepCopy() *WarpgateRoleStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTarget) DeepCopyInto(out *WarpgateTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTarget.
func (in *WarpgateTarget) DeepCopy() *WarpgateTarget {
	if in == nil {
		return nil
	}
	out := new(WarpgateTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetCustomDefaulter) DeepCopyInto(out *WarpgateTargetCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetCustomDefaulter.
func (in *WarpgateTargetCustomDefaulter) DeepCopy() *WarpgateTargetCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetCustomValidator) DeepCopyInto(out *WarpgateTargetCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetCustomValidator.
func (in *WarpgateTargetCustomValidator) DeepCopy() *WarpgateTargetCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetList) DeepCopyInto(out *WarpgateTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetList.
func (in *WarpgateTargetList) DeepCopy() *WarpgateTargetList {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRole) DeepCopyInto(out *WarpgateTargetRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRole.
func (in *WarpgateTargetRole) DeepCopy() *WarpgateTargetRole {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTargetRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRoleCustomDefaulter) DeepCopyInto(out *WarpgateTargetRoleCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRoleCustomDefaulter.
func (in *WarpgateTargetRoleCustomDefaulter) DeepCopy() *WarpgateTargetRoleCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRoleCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRoleCustomValidator) DeepCopyInto(out *WarpgateTargetRoleCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRoleCustomValidator.
func (in *WarpgateTargetRoleCustomValidator) DeepCopy() *WarpgateTargetRoleCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRoleCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRoleList) DeepCopyInto(out *WarpgateTargetRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateTargetRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRoleList.
func (in *WarpgateTargetRoleList) DeepCopy() *WarpgateTargetRoleList {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTargetRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRoleSpec) DeepCopyInto(out *WarpgateTargetRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRoleSpec.
func (in *WarpgateTargetRoleSpec) DeepCopy() *WarpgateTargetRoleSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetRoleStatus) DeepCopyInto(out *WarpgateTargetRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetRoleStatus.
func (in *WarpgateTargetRoleStatus) DeepCopy() *WarpgateTargetRoleStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetSpec) DeepCopyInto(out *WarpgateTargetSpec) {
	*out = *in
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSHTargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPTargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLTargetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLTargetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetSpec.
func (in *WarpgateTargetSpec) DeepCopy() *WarpgateTargetSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTargetStatus) DeepCopyInto(out *WarpgateTargetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTargetStatus.
func (in *WarpgateTargetStatus) DeepCopy() *WarpgateTargetStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicket) DeepCopyInto(out *WarpgateTicket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicket.
func (in *WarpgateTicket) DeepCopy() *WarpgateTicket {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTicket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicketCustomDefaulter) DeepCopyInto(out *WarpgateTicketCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicketCustomDefaulter.
func (in *WarpgateTicketCustomDefaulter) DeepCopy() *WarpgateTicketCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicketCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicketCustomValidator) DeepCopyInto(out *WarpgateTicketCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicketCustomValidator.
func (in *WarpgateTicketCustomValidator) DeepCopy() *WarpgateTicketCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicketCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicketList) DeepCopyInto(out *WarpgateTicketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateTicket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicketList.
func (in *WarpgateTicketList) DeepCopy() *WarpgateTicketList {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateTicketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicketSpec) DeepCopyInto(out *WarpgateTicketSpec) {
	*out = *in
	if in.NumberOfUses != nil {
		in, out := &in.NumberOfUses, &out.NumberOfUses
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicketSpec.
func (in *WarpgateTicketSpec) DeepCopy() *WarpgateTicketSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateTicketStatus) DeepCopyInto(out *WarpgateTicketStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateTicketStatus.
func (in *WarpgateTicketStatus) DeepCopy() *WarpgateTicketStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateTicketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUser) DeepCopyInto(out *WarpgateUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUser.
func (in *WarpgateUser) DeepCopy() *WarpgateUser {
	if in == nil {
		return nil
	}
	out := new(WarpgateUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserCustomDefaulter) DeepCopyInto(out *WarpgateUserCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserCustomDefaulter.
func (in *WarpgateUserCustomDefaulter) DeepCopy() *WarpgateUserCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserCustomValidator) DeepCopyInto(out *WarpgateUserCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserCustomValidator.
func (in *WarpgateUserCustomValidator) DeepCopy() *WarpgateUserCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserList) DeepCopyInto(out *WarpgateUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserList.
func (in *WarpgateUserList) DeepCopy() *WarpgateUserList {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRole) DeepCopyInto(out *WarpgateUserRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRole.
func (in *WarpgateUserRole) DeepCopy() *WarpgateUserRole {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateUserRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRoleCustomDefaulter) DeepCopyInto(out *WarpgateUserRoleCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRoleCustomDefaulter.
func (in *WarpgateUserRoleCustomDefaulter) DeepCopy() *WarpgateUserRoleCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRoleCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRoleCustomValidator) DeepCopyInto(out *WarpgateUserRoleCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRoleCustomValidator.
func (in *WarpgateUserRoleCustomValidator) DeepCopy() *WarpgateUserRoleCustomValidator {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRoleCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRoleList) DeepCopyInto(out *WarpgateUserRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WarpgateUserRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRoleList.
func (in *WarpgateUserRoleList) DeepCopy() *WarpgateUserRoleList {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WarpgateUserRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRoleSpec) DeepCopyInto(out *WarpgateUserRoleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRoleSpec.
func (in *WarpgateUserRoleSpec) DeepCopy() *WarpgateUserRoleSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserRoleStatus) DeepCopyInto(out *WarpgateUserRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserRoleStatus.
func (in *WarpgateUserRoleStatus) DeepCopy() *WarpgateUserRoleStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserSpec) DeepCopyInto(out *WarpgateUserSpec) {
	*out = *in
	if in.CredentialPolicy != nil {
		in, out := &in.CredentialPolicy, &out.CredentialPolicy
		*out = new(CredentialPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GeneratePassword != nil {
		in, out := &in.GeneratePassword, &out.GeneratePassword
		*out = new(bool)
		**out = **in
	}
	if in.PasswordLength != nil {
		in, out := &in.PasswordLength, &out.PasswordLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserSpec.
func (in *WarpgateUserSpec) DeepCopy() *WarpgateUserSpec {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarpgateUserStatus) DeepCopyInto(out *WarpgateUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarpgateUserStatus.
func (in *WarpgateUserStatus) DeepCopy() *WarpgateUserStatus {
	if in == nil {
		return nil
	}
	out := new(WarpgateUserStatus)
	in.DeepCopyInto(out)
	return out
}
